# Top navigation menus
menu:
    Home: /
    Archives: /archives/

# Site Images
favicon: /favicon.ico
logo: /logo.png
# Profiles
#profile: /image/profile.jpg
#profile_url: https://github.com/stunstunstun
# Google Analytics
ga:
# Facebook App Id for Comments
fb:
# Facebook Page URL
fb_page:
# Copyright Infomation
startyear: 2017
